Add basic docs for Docker, binary compiled to work w/o glibc
mtulio/statuscake-exporter pull request #21
Opened 2019-11-19 22:09 UTC by mattsimonsen

The CGO_ENABLED flag was breaking compatibility with alpine linux, which does not support glibc.  

Please let me know if you need anything else to get this merged, the Docker file works great for me so hopefully the little documentation will help others.

2019-11-20 21:30 UTC, mtulio requested changes

2019-11-20 21:30 UTC, mtulio commented on hack/Dockerfile-goreleaser
> -FROM alpine:latest
I need this Dockerfile to use with `goreleaser` tool and automate the cross build.

2019-11-20 21:36 UTC, mattsimonsen commented on hack/Dockerfile-goreleaser
> -FROM alpine:latest
I've merged to fix an updated documentation file, and added the second Dockerfile back.

2019-11-20 22:36 UTC, mtulio approved these changes
LGTM. Please rebase to merge.
Thanks

2019-11-20 22:55 UTC, mattsimonsen commented
> LGTM. Please rebase to merge.
> Thanks


Apologies, please let me know if the rebase isn't as hoped.  

I believe my updated commit will apply cleanly.

2019-11-21 01:18 UTC, mtulio approved these changes

2019-11-21 11:50 UTC, mtulio requested changes
Hi @mattsimonsen , I've suggested small changes. :)
Thanks.

2019-11-21 11:50 UTC, mtulio commented on Makefile
> +	 CGO_ENABLED=$(CGO_ENABLED) GOOS=$(GOOS) GOARCH=$(GOARCH) \
```suggestion
	CGO_ENABLED=$(CGO_ENABLED) GOOS=$(GOOS) GOARCH=$(GOARCH) \
```

2019-11-21 11:50 UTC, mtulio commented on Makefile
> +		go build  \
```suggestion
		go build \
```

2019-11-21 11:50 UTC, mtulio commented on Makefile-glob.mk
> +
```suggestion
```

2019-11-24 20:28 UTC, mtulio approved these changes

2019-11-24 20:28 UTC, merged

2019-11-24 20:28 UTC, mtulio commented
Thanks @mattsimonsen